run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Standard Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Find unused code
    - gofmt         # Check formatting
    - goimports     # Check imports
    - misspell      # Find misspellings
    - unconvert     # Remove unnecessary conversions
    - unparam       # Find unused function parameters
    - gocritic      # Opinionated checks
    - revive        # Fast, configurable, extensible linter
    - stylecheck    # Style checks
    - gosec         # Security checks

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/ECecillo/lib.go.sound

  misspell:
    locale: US

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - ifElseChain

  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: var-naming
        severity: warning

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - unparam
        - gocritic

    # Exclude magic number checks in tests
    - path: _test\.go
      text: "mnd:"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true
