version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - commentedOutCode
        - ifElseChain
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      enable-all: true
    misspell:
      locale: US
    revive:
      severity: warning
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
        - name: var-naming
          severity: warning
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - gosec
          - unparam
        path: _test\.go
      - path: _test\.go
        text: 'mnd:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
